services:
  app:
    build: .
    container_name: proyecto-php74
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    container_name: proyecto-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net

  db:
    image: mysql:5.7
    container_name: proyecto-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
